### PR TITLE
Initialize more fields in CrashDetails constructor

### LINKED ISSUE #200: CrashDetails.writeCrashReport() throws Exception for uninitialized fields
I have implemented my own `NativeCrashManager` and I make use of the `CrashDetails` class to write a crash report log.  However, I noticed that I had to set a few member variables that I didn't particularly care about in order to avoid an exception.

Code to reproduce:
```
CrashDetails crashDetails = new CrashDetails("1234");
crashDetails.writeCrashReport();
```

Expected Results:
No Exception

Actual Results:
Exception because `appStartDate`, `appCrashDate`, `isXamarinException` or `throwableStackTrace` is null.

Minimum code to avoid an Exception:
```
CrashDetails crashDetails = new CrashDetails("1234");
crashDetails.setAppStartDate(new Date());
crashDetails.setAppCrashDate(new Date());
crashDetails.setIsXamarinException(false);
crashDetails.setThrowableStackTrace("");
crashDetails.writeCrashReport();
```

### PR DESCRIPTION
**Pull request by fivemicro**
In order to avoid an Exception when calling writeCrashReport, initialize
the following members to default values:
* appStartDate
* appCrashDate
* isXamarinException
* throwableStackTrace

Fixes #200

### CODE REVIEW

**Comment by fivemicro** [comment]
Sorry to be a nag, but could @ranterle or @TroubleMakerBen review this PR?

File: hockeysdk/src/main/java/net/hockeyapp/android/objects/CrashDetails.java [hunk 1]
```diff
@@ -56,6 +56,10 @@
 
     public CrashDetails(String crashIdentifier) {
         this.crashIdentifier = crashIdentifier;
+        appStartDate = new Date();
```
Comment (ranterle) [inline hockeysdk/src/main/java/net/hockeyapp/android/objects/CrashDetails.java]: These two lines are dangerous, since the values might not be true in this case, so they are not sensible default values. They should be `null`. The code causing the exception you're experiencing should be handling the `null` case instead to either gracefully handle it (not recommended since we rely on these fields) or throw a more reasonable exception.
Overriding the `CrashManager` / `ExceptionHandler` or building your own should produce the same valid crash report files.

Comment (fivemicro) [inline hockeysdk/src/main/java/net/hockeyapp/android/objects/CrashDetails.java]: @ranterle - I hear what you are saying.  How about the 2 lines below?
```
isXamarinException = false;
throwableStackTrace = "";
```

If I gave you a new PR with just those 2 lines would you merge it?  If not, how about just `isXamarinException = false;` ?  The other constructors all set a value for `isXamarinException`.

Comment (ranterle) [inline hockeysdk/src/main/java/net/hockeyapp/android/objects/CrashDetails.java]: No need for a new PR, just update this one to, so there's only

```
isXamarinException = false;
throwableStackTrace = "";
```

Otherwise this looks good to me.

**Comment by fivemicro** [comment]
Thanks @ranterle .  I have pushed an additional commit to address your requested changes.
